-- CREATE DATABASE COFFEE_HOUSE;

CREATE TABLE CLIENTS -- Клиенты
(
	ID SERIAL NOT NULL,
	NAME TEXT NOT NULL,
	SECONDNAME TEXT NOT NULL,
	SURNAME TEXT,
	ADRESS TEXT,
	PHONE TEXT UNIQUE,
	EMAIL TEXT UNIQUE,
	PRIMARY KEY(ID)
);

CREATE TABLE MENU_POSITIONS -- Позиции меню
(
	ID SERIAL NOT NULL,
	NAME TEXT NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE MENU -- Меню
(
	ID SERIAL NOT NULL,
	NAME TEXT NOT NULL,
	QUANTITY INTEGER, --Количество
	PRIMARY KEY(ID),
	FOREIGN KEY(ID) REFERENCES CLIENTS(ID),
	FOREIGN KEY(ID) REFERENCES MENU_POSITIONS(ID)
);

CREATE TABLE EMPLOYEES -- Сотрудники
(
	ID SERIAL NOT NULL,
	NAME TEXT NOT NULL,
	SECONDNAME TEXT NOT NULL,
	SURNAME TEXT,
	TAXNUMBER TEXT UNIQUE, -- ИНН
	PRIMARY KEY(ID)
);

CREATE TABLE "ORDER" -- Заказ
(
	ID SERIAL NOT NULL,
	DATE_START DATE NOT NULL, -- Дата окрытия заказа
	DATE_END DATE, -- Дата закрытия заказа
	STATE_ORDER TEXT, -- Статус заказа
	PRIMARY KEY(ID),
	FOREIGN KEY(ID) REFERENCES EMPLOYEES(ID),
	FOREIGN KEY(ID) REFERENCES MENU(ID)
);

CREATE TABLE MATERIALS -- Сырьё
(
	ID SERIAL NOT NULL,
	NAME TEXT NOT NULL,
	PRICE MONEY NOT NULL,
	QUANTITY INTEGER, -- Количество
	PRIMARY KEY (ID)
);

CREATE TABLE SERVICE --Услуги
(
	ID SERIAL NOT NULL,
	NAME TEXT,
	PRICE MONEY NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID) REFERENCES MATERIALS(ID),
	FOREIGN KEY(ID) REFERENCES "ORDER"(ID)
);

CREATE TABLE RECEIPT -- Чек
(
	ID SERIAL NOT NULL,
	SERVICE TEXT NOT NULL,
	PRICE MONEY NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID) REFERENCES SERVICE(ID)
);